sudo: required

services:
  - docker

matrix:
  include:
    - if: branch =~ back
    
      script: cd back && ./build-docker.sh

    - if: branch =~ front
    
      script: cd front && ./build-docker.sh