sudo: required

services:
  - docker

matrix:
  include:
    - if: branch =~ back
    
      script: cd back && ./build-docker.sh

    - if: branch =~ front
    
      script: cd front && ./build-docker.sh

    - if: branch = services/weather
    
      script: cd back/services/haskell/weather && ./build-docker-server.sh

    - if: branch = services/weather
    
      script: cd back/services/haskell/weather && ./build-docker-scheduler.sh

    - if: branch = services/weather-docker
    
      script: cd back/services/haskell/weather && ./build-docker-base.sh
