FROM goncharovnikita/website:weather-base as builder

WORKDIR /app/weather

COPY . /app/weather

RUN cabal install --install-method=copy --overwrite-policy=always weather-server

FROM phadej/ghc:8.6.5-bionic-slim as worker

WORKDIR /app

COPY --from=builder /root/.cabal/bin/weather-server .

CMD ["./weather-server"]
